---

- name: Register | lukscrypt_blockdev_part1
  shell: lsblk -l -n -o NAME {{ lukscrypt_blockdev }} | grep -e '.*1$'
  register: lukscrypt_blockdev_part1
  changed_when: false

- name: Register | lukscrypt_blockdev_p1_fs_type
  command: blkid -o value -s TYPE  /dev/{{ lukscrypt_blockdev_part1.stdout }}
  register: lukscrypt_blockdev_p1_fs_type
  ignore_errors: true
  when:
    - lukscrypt_blockdev_part1.stdout != ""
  changed_when: false

- name: Format EFI partiion
  command: mkfs.vfat -F32 "/dev/{{ lukscrypt_blockdev_part1.stdout }}"
  when:
    - not lukscrypt_blockdev_p1_fs_type.stdout|search("vfat")
    - lukscrypt_blockdev_part1.stdout != ""

- name: Register | lukscrypt_blockdev_part2
  shell: lsblk -l -n -o NAME {{ lukscrypt_blockdev }} | grep -e '.*2$'
  register: lukscrypt_blockdev_part2
  changed_when: false

- name: Format BOOT partition
  filesystem:
    dev: "/dev/{{ lukscrypt_blockdev_part2.stdout }}"
    fstype: btrfs
    opts: -m single

- name: Format lv root
  filesystem:
    dev: "/dev/mapper/{{ lukscrypt_vg_name}}-root"
    fstype: btrfs
    opts: -m single

- name: Format lv home
  filesystem:
    dev: "/dev/mapper/{{ lukscrypt_vg_name }}-home"
    fstype: xfs

- name: Register | lukscrypt_lv_swap_fs_type
  command: blkid -o value -s TYPE "/dev/mapper/{{ lukscrypt_vg_name }}-swap"
  register: lukscrypt_lv_swap_fs_type
  ignore_errors: true
  changed_when: false

- name: Format lv swap
  command: mkswap "/dev/mapper/{{ lukscrypt_vg_name }}-swap"
  when: not lukscrypt_lv_swap_fs_type.stdout|search("swap")
